name: Run PHP script
on: 
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, curl
          ini-values: output_buffering=On
          tools: composer
      - name: Build Static Site
        run: php script.php      
      - name: Commit Build
        uses: stefanzweifel/git-auto-commit-action@v4
      - name: Deploy Build
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deploy
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
